# CreateLocalUsers.ps1
# Script interativo para criar utilizadores locais a partir de user:pass
# Inclui banners azuis, resumo final e opcao de promover alguns utilizadores a administradores

function Show-Banner($text) {
    Write-Host ""
        Write-Host "############################################################" -ForegroundColor White -BackgroundColor DarkBlue
            Write-Host "#                                                          #" -ForegroundColor White -BackgroundColor DarkBlue
                $padding = (60 - $text.Length) / 2
                    $line = (" " * [Math]::Floor($padding)) + $text + (" " * [Math]::Ceiling($padding))
                        Write-Host "#$line#" -ForegroundColor White -BackgroundColor DarkBlue
                            Write-Host "#                                                          #" -ForegroundColor White -BackgroundColor DarkBlue
                                Write-Host "############################################################" -ForegroundColor White -BackgroundColor DarkBlue
                                    Write-Host ""
                                    }

                                    # Banner inicial
                                    Clear-Host
                                    Show-Banner "SCRIPT DE CRIACAO DE UTILIZADORES LOCAIS"

                                    # Perguntar pelo ficheiro
                                    $UserListFile = Read-Host "Indique o caminho completo do ficheiro (ex: C:\Users\Public\userlist.txt)"

                                    if (-Not (Test-Path $UserListFile)) {
                                        Write-Host "Ficheiro nao encontrado: $UserListFile" -ForegroundColor Red
                                            exit
                                            }

                                            Write-Host "Ficheiro encontrado: $UserListFile" -ForegroundColor Green
                                            Write-Host ""

                                            # Perguntar pelos utilizadores que devem ser admins
                                            $adminInput = Read-Host "Indique os utilizadores (separados por virgulas) que devem ser administradores (ou deixe vazio para nenhum)"
                                            $adminList = @()
                                            if (-not [string]::IsNullOrWhiteSpace($adminInput)) {
                                                $adminList = $adminInput.Split(",") | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }
                                                }

                                                Write-Host "----------------------------------------------"

                                                # Contadores
                                                $created = 0
                                                $skipped = 0
                                                $errors = 0
                                                $promoted = 0
                                                $adminErrors = @()

                                                # Ler e processar cada linha
                                                $lines = Get-Content $UserListFile
                                                $total = $lines.Count
                                                $index = 1

                                                foreach ($line in $lines) {
                                                    Write-Host "[$index/$total] A processar linha: $line" -ForegroundColor Yellow

                                                        try {
                                                                $parts = $line.Split(":")
                                                                        $username = $parts[0].Trim()
                                                                                $password = $parts[1].Trim()

                                                                                        if ([string]::IsNullOrWhiteSpace($username) -or [string]::IsNullOrWhiteSpace($password)) {
                                                                                                    Write-Host "Linha invalida: '$line' - ignorada." -ForegroundColor DarkYellow
                                                                                                                $skipped++
                                                                                                                        }
                                                                                                                                elseif (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
                                                                                                                                            Write-Host "Utilizador '$username' ja existe - ignorado." -ForegroundColor Gray
                                                                                                                                                        $skipped++
                                                                                                                                                                }
                                                                                                                                                                        else {
                                                                                                                                                                                    $securePass = ConvertTo-SecureString $password -AsPlainText -Force
                                                                                                                                                                                                New-LocalUser -Name $username -Password $securePass -FullName $username -Description "Conta criada por script" -PasswordNeverExpires
                                                                                                                                                                                                            Add-LocalGroupMember -Group "Users" -Member $username
                                                                                                                                                                                                                        Write-Host "Utilizador '$username' criado com sucesso (grupo: Users)." -ForegroundColor Green
                                                                                                                                                                                                                                    $created++
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    catch {
                                                                                                                                                                                                                                                            Write-Host "Erro ao criar '$username' -> $($_.Exception.Message)" -ForegroundColor Red
                                                                                                                                                                                                                                                                    $errors++
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                            $index++
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            # Promover admins
                                                                                                                                                                                                                                                                            if ($adminList.Count -gt 0) {
                                                                                                                                                                                                                                                                                Write-Host ""
                                                                                                                                                                                                                                                                                    Write-Host "=== Atribuir permissoes de Administrador ===" -ForegroundColor Cyan
                                                                                                                                                                                                                                                                                        foreach ($adminUser in $adminList) {
                                                                                                                                                                                                                                                                                                if (Get-LocalUser -Name $adminUser -ErrorAction SilentlyContinue) {
                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                            Add-LocalGroupMember -Group "Administrators" -Member $adminUser -ErrorAction Stop
                                                                                                                                                                                                                                                                                                                                            Write-Host "'$adminUser' promovido a Administrador." -ForegroundColor Green
                                                                                                                                                                                                                                                                                                                                                            $promoted++
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    catch {
                                                                                                                                                                                                                                                                                                                                                                                                    Write-Host "Erro ao promover '$adminUser' -> $($_.Exception.Message)" -ForegroundColor Red
                                                                                                                                                                                                                                                                                                                                                                                                                    $adminErrors += $adminUser
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Write-Host "Utilizador '$adminUser' nao encontrado - nao foi promovido." -ForegroundColor Red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $adminErrors += $adminUser
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Banner final com resumo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Show-Banner "RESUMO DA EXECUCAO"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write-Host "Utilizadores criados   : $created" -ForegroundColor Green
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write-Host "Ignorados              : $skipped" -ForegroundColor Yellow
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write-Host "Erros na criacao       : $errors" -ForegroundColor Red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Write-Host "Promovidos a admin     : $promoted" -ForegroundColor Cyan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($adminErrors.Count -gt 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Write-Host "Nao foi possivel promover os seguintes a admin:" -ForegroundColor Red
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $adminErrors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Write-Host "----------------------------------------------"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Write-Host "Fim do script." -ForegroundColor Cyan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Write-Host ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
